sharding:
      jdbc:
        dataSource:
          names: db-test0,db-test1,db-test2 # 多个数据源的名称
          # 配置主库
          db-test0: #org.apache.tomcat.jdbc.pool.DataSource
            type: com.alibaba.druid.pool.DruidDataSource
            driverClassName: com.mysql.jdbc.Driver
            url: jdbc:mysql://192.168.174.129:3306/cool?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
            username: root
            password: 123456
            #最大连接数
            maxPoolSize: 20
          db-test1: # 配置第一个从库
            type: com.alibaba.druid.pool.DruidDataSource
            driverClassName: com.mysql.jdbc.Driver
            url: jdbc:mysql://192.168.174.130:3306/cool?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
            username: root
            password: 123456
            #最大连接数
            maxPoolSize: 20
          db-test2: # 配置第二个从库
            type: com.alibaba.druid.pool.DruidDataSource
            driverClassName: com.mysql.jdbc.Driver
            url: jdbc:mysql://192.168.174.131:3306/cool?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false&useSSL=false&serverTimezone=GMT
            username: root
            password: 123456
            #最大连接数
            maxPoolSize: 20
        config:
          masterslave: #读写分离配置
            load-balance-algorithm-type: round_robin # 配置从库选择策略，提供轮询与随机，这里选择用轮询//random 随机 //round_robin 轮询
            name: db1s2
            master-data-source-name: db-test0 # 主数据源名称
            slave-data-source-names: db-test1,db-test2 # 从数据源名称，多个用逗号分隔
        props:
          sql: # 开启sql显示，默认值是false，注意：仅配置读写分离时不会打印日志
            show: true

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
